let CountryData = [
{ "name": "Aland Islands", "demonym": "Alandic" },
{ "name": "Algeria", "demonym": "Algerian" },
{ "name": "American Samoa", "demonym": "American Samoan" },
{ "name": "Andorra", "demonym": "Andorran" },
{ "name": "Angola", "demonym": "Angolan" },
{ "name": "Anguilla", "demonym": "Anguillian" },
{ "name": "Antigua and Barbuda", "demonym": "Antiguan Barbudan" },
{ "name": "Argentina", "demonym": "Argentinian" },
{ "name": "Armenia", "demonym": "Armenian" },
{ "name": "Aruba", "demonym": "Arubian" },
{ "name": "Australia", "demonym": "Australian" },
{ "name": "Austria", "demonym": "Austrian" },
{ "name": "Azerbaijan", "demonym": "Azerbaijani" },
{ "name": "Bahamas", "demonym": "Bahamian" },
{ "name": "Bahrain", "demonym": "Bahraini" },
{ "name": "Bangladesh", "demonym": "Bengali" },
{ "name": "Barbados", "demonym": "Barbadian" },
{ "name": "Belarus", "demonym": "Belarusian" },
{ "name": "Belgium", "demonym": "Belgian" },
{ "name": "Belize", "demonym": "Belizean" },
{ "name": "Benin", "demonym": "Beninese" },
{ "name": "Bermuda", "demonym": "Bermudian" },
{ "name": "Bhutan", "demonym": "Bhutanese" },
{ "name": "Bolivia", "demonym": "Bolivian" },
{ "name": "Bonaire, Sint Eustatius and Saba", "demonym": "Dutch" },
{ "name": "Bosnia and Herzegovina", "demonym": "Bosnian" },
{ "name": "Botswana", "demonym": "Batswana" },
{ "name": "Brazil", "demonym": "Brazilian" },
{ "name": "British Virgin Islands", "demonym": "Virgin Islander" },
{ "name": "Brunei", "demonym": "Bruneian" },
{ "name": "Bulgaria", "demonym": "Bulgarian" },
{ "name": "Burkina Faso", "demonym": "Burkinabé" },
{ "name": "Burundi", "demonym": "Burundian" },
{ "name": "Cambodia", "demonym": "Cambodian" },
{ "name": "Cameroon", "demonym": "Cameroonian" },
{ "name": "Canada", "demonym": "Canadian" },
{ "name": "Cape Verde", "demonym": "Cape Verdean" },
{ "name": "Cayman Islands", "demonym": "Caymanian" },
{ "name": "Central African Republic", "demonym": "Central African" },
{ "name": "Chad", "demonym": "Chadian" },
{ "name": "Chile", "demonym": "Chilean" },
{ "name": "China", "demonym": "Chinese" },
{ "name": "Christmas Island", "demonym": "Christmas Islander" },
{ "name": "Cocos Islands", "demonym": "Taiwanese" },
{ "name": "Colombia", "demonym": "Colombian" },
{ "name": "Comoros", "demonym": "Comorian" },
{ "name": "Congo", "demonym": "Congolese" },
{ "name": "Cook Islands", "demonym": "Cook Islander" },
{ "name": "Costa Rica", "demonym": "Costa Rican" },
{ "name": "Côte d'Ivoire", "demonym": "Ivorian" },
{ "name": "Croatia", "demonym": "Croatian" },
{ "name": "Cuba", "demonym": "Cuban" },
{ "name": "Curaçao", "demonym": "Dutch" },
{ "name": "Cyprus", "demonym": "Cypriot" },
{ "name": "Czech Republic", "demonym": "Czech" },
{ "name": "Democratic Republic of the Congo", "demonym": "Congolese" },
{ "name": "Denmark", "demonym": "Danish" },
{ "name": "Djibouti", "demonym": "Djiboutian" },
{ "name": "Dominica", "demonym": "Dominican" },
{ "name": "Dominican Republic", "demonym": "Dominican" },
{ "name": "Ecuador", "demonym": "Ecuadorian" },
{ "name": "Egypt", "demonym": "Egyptian" },
{ "name": "El Salvador", "demonym": "Salvadoran" },
{ "name": "Equatorial Guinea", "demonym": "Equatoguinean" },
{ "name": "Eritrea", "demonym": "Eritrean" },
{ "name": "Estonia", "demonym": "Estonian" },
{ "name": "Ethiopia", "demonym": "Ethiopian" },
{ "name": "Falkland Islands", "demonym": "Falkland Islander" },
{ "name": "Faroe Islands", "demonym": "Faroese" },
{ "name": "Fiji", "demonym": "Fijian" },
{ "name": "Finland", "demonym": "Finnish" },
{ "name": "France", "demonym": "French" },
{ "name": "French Guiana", "demonym": "Guianan" },
{ "name": "French Polynesia", "demonym": "French Polynesian" },
{ "name": "Gabon", "demonym": "Gabonese" },
{ "name": "Gambia", "demonym": "Gambian" },
{ "name": "Georgia", "demonym": "Georgian" },
{ "name": "Germany", "demonym": "German" },
{ "name": "Ghana", "demonym": "Ghanaian" },
{ "name": "Gibraltar", "demonym": "Gibraltarian" },
{ "name": "Greece", "demonym": "Greek" },
{ "name": "Greenland", "demonym": "Greenlander" },
{ "name": "Grenada", "demonym": "Grenadian" },
{ "name": "Guadeloupe", "demonym": "Guadeloupean" },
{ "name": "Guam", "demonym": "Guamanian" },
{ "name": "Guatemala", "demonym": "Guatemalan" },
{ "name": "Guernsey", "demonym": "Guernseymen" },
{ "name": "Guinea-Bissau", "demonym": "Bissau-Guinean" },
{ "name": "Guinea", "demonym": "Guinean" },
{ "name": "Guyana", "demonym": "Guyanese" },
{ "name": "Haiti", "demonym": "Haitian" },
{ "name": "Holy See", "demonym": "Papal" },
{ "name": "Honduras", "demonym": "Honduran" },
{ "name": "Hong Kong", "demonym": "Hong Kongese" },
{ "name": "Hungary", "demonym": "Hungarian" },
{ "name": "Iceland", "demonym": "Icelander" },
{ "name": "India", "demonym": "Indian" },
{ "name": "Indonesia", "demonym": "Indonesian" },
{ "name": "British Indian Ocean Territory", "demonym": "British" },
{ "name": "Iran", "demonym": "Iranian" },
{ "name": "Iraq", "demonym": "Iraqi" },
{ "name": "Ireland", "demonym": "Irish" },
{ "name": "Isle of Man", "demonym": "Manx" },
{ "name": "Israel", "demonym": "Israeli" },
{ "name": "Italy", "demonym": "Italian" },
{ "name": "Jamaica", "demonym": "Jamaican" },
{ "name": "Japan", "demonym": "Japanese" },
{ "name": "Jersey", "demonym": "Jerseyman" },
{ "name": "Jordan", "demonym": "Jordanian" },
{ "name": "Kazakhstan", "demonym": "Kazakhstani" },
{ "name": "Kenya", "demonym": "Kenyan" },
{ "name": "Kiribati", "demonym": "I-Kiribati" },
{ "name": "Kosovo", "demonym": "Kosovar" },
{ "name": "Kuwait", "demonym": "Kuwaiti" },
{ "name": "Kyrgyzstan", "demonym": "Kyrgyzstani" },
{ "name": "Laos", "demonym": "Lao" },
{ "name": "Latvia", "demonym": "Latvian" },
{ "name": "Lebanon", "demonym": "Lebanese" },
{ "name": "Lesotho", "demonym": "Lesothonian" },
{ "name": "Liberia", "demonym": "Liberian" },
{ "name": "Libya", "demonym": "Libyan" },
{ "name": "Liechtenstein", "demonym": "Liechtensteiner" },
{ "name": "Lithuania", "demonym": "Lithuanian" },
{ "name": "Luxembourg", "demonym": "Luxembourgish" },
{ "name": "Macao", "demonym": "Macau" },
{ "name": "Madagascar", "demonym": "Malagasy" },
{ "name": "Malawi", "demonym": "Malawian" },
{ "name": "Malaysia", "demonym": "Malaysian" },
{ "name": "Maldives", "demonym": "Maldivian" },
{ "name": "Mali", "demonym": "Malian" },
{ "name": "Malta", "demonym": "Maltese" },
{ "name": "Marshall Islands", "demonym": "Marshallese" },
{ "name": "Martinique", "demonym": "Martinican" },
{ "name": "Mauritania", "demonym": "Mauritanian" },
{ "name": "Mauritius", "demonym": "Mauritian" },
{ "name": "Mayotte", "demonym": "Mahoran" },
{ "name": "Mexico", "demonym": "Mexican" },
{ "name": "Micronesia", "demonym": "Micronesian" },
{ "name": "Moldova", "demonym": "Moldovan" },
{ "name": "Monaco", "demonym": "Monegasque" },
{ "name": "Mongolia", "demonym": "Mongolian" },
{ "name": "Montenegro", "demonym": "Montenegrin" },
{ "name": "Montserrat", "demonym": "Montserratian" },
{ "name": "Morocco", "demonym": "Moroccan" },
{ "name": "Mozambique", "demonym": "Mozambican" },
{ "name": "Myanmar", "demonym": "Myanma" },
{ "name": "Namibia", "demonym": "Namibian" },
{ "name": "Nauru", "demonym": "Nauruan" },
{ "name": "Nepal", "demonym": "Nepalese" },
{ "name": "Netherlands Antilles", "demonym": "Netherlands Antillean" },
{ "name": "Netherlands", "demonym": "Dutch" },
{ "name": "New Caledonia", "demonym": "New Caledonian" },
{ "name": "New Zealand", "demonym": "New Zealander" },
{ "name": "Nicaragua", "demonym": "Nicaraguan" },
{ "name": "Niger", "demonym": "Nigerien" },
{ "name": "Nigeria", "demonym": "Nigerian" },
{ "name": "Niue", "demonym": "Niuean" },
{ "name": "Norfolk Island", "demonym": "Norfolk Islander" },
{ "name": "North Korea", "demonym": "North Korea" },
{ "name": "North Macedonia", "demonym": "Macedonian" },
{ "name": "Northern Mariana Islands", "demonym": "Northern Mariana Islander" },
{ "name": "Norway", "demonym": "Norwegian" },
{ "name": "Oman", "demonym": "Omani" },
{ "name": "Pakistan", "demonym": "Pakistani" },
{ "name": "Palau", "demonym": "Palauan" },
{ "name": "Palestine", "demonym": "Palestinian" },
{ "name": "Panama", "demonym": "Panamanian" },
{ "name": "Papua New Guinea", "demonym": "Papua New Guinean" },
{ "name": "Paraguay", "demonym": "Paraguayan" },
{ "name": "Peru", "demonym": "Peruvian" },
{ "name": "Philippines", "demonym": "Filipino" },
{ "name": "Pitcairn", "demonym": "Pitcairn Islander" },
{ "name": "Poland", "demonym": "Polish" },
{ "name": "Portugal", "demonym": "Portuguese" },
{ "name": "Puerto Rico", "demonym": "Puerto Rican" },
{ "name": "Qatar", "demonym": "Qatari" },
{ "name": "Réunion", "demonym": "Réunionese" },
{ "name": "Romania", "demonym": "Romanian" },
{ "name": "Russia", "demonym": "Russian" },
{ "name": "Rwanda", "demonym": "Rwandan" },
{ "name": "Saint Barthélemy", "demonym": "Barthélemois" },
{ "name": "Saint Helena, Ascension and Tristan da Cunha", "demonym": "Ascensionian" },
{ "name": "Saint Kitts and Nevis", "demonym": "Kittitian" },
{ "name": "Saint Lucia", "demonym": "Saint Lucian" },
{ "name": "Saint Martin", "demonym": "Saint-Martinois" },
{ "name": "Saint Pierre and Miquelon", "demonym": "Saint-Pierrais" },
{ "name": "Saint Vincent and the Grenadines", "demonym": "Saint Vincentian" },
{ "name": "Samoa", "demonym": "Samoan" },
{ "name": "San Marino", "demonym": "Sammarinese" },
{ "name": "Sao Tome and Principe", "demonym": "São Toméan" },
{ "name": "Saudi Arabia", "demonym": "Saudi" },
{ "name": "Senegal", "demonym": "Senegalese" },
{ "name": "Serbia", "demonym": "Serbian" },
{ "name": "Seychelles", "demonym": "Seychellois" },
{ "name": "Sierra Leone", "demonym": "Sierra Leonean" },
{ "name": "Singapore", "demonym": "Singaporean" },
{ "name": "Sint Maarten", "demonym": "St. Maartener" },
{ "name": "Slovakia", "demonym": "Slovak" },
{ "name": "Slovenia", "demonym": "Slovenian" },
{ "name": "Solomon Islands", "demonym": "Solomon Islander" },
{ "name": "Somalia", "demonym": "Somali" },
{ "name": "South Africa", "demonym": "South African" },
{ "name": "South Georgia and the South Sandwich Islands", "demonym": "South Georgian" },
{ "name": "South Korea", "demonym": "South Korean" },
{ "name": "South Sudan", "demonym": "South Sudanese" },
{ "name": "Spain", "demonym": "Spanish" },
{ "name": "Sri Lanka", "demonym": "Sri Lankan" },
{ "name": "Sudan", "demonym": "Sudanese" },
{ "name": "Svalbard and Jan Mayen", "demonym": "Svalbard" },
{ "name": "Swaziland", "demonym": "Swazi" },
{ "name": "Sweden", "demonym": "Swedish" },
{ "name": "Switzerland", "demonym": "Swiss" },
{ "name": "Syria", "demonym": "Syrian" },
{ "name": "Taiwan", "demonym": "Taiwanese" },
{ "name": "Tajikistan", "demonym": "Tajik" },
{ "name": "Tanzania", "demonym": "Tanzanian" },
{ "name": "Thailand", "demonym": "Thai" },
{ "name": "Timor-Leste", "demonym": "Timorese" },
{ "name": "Togo", "demonym": "Togolese" },
{ "name": "Tokelau", "demonym": "Tokelauan" },
{ "name": "Tonga", "demonym": "Tongan" },
{ "name": "Trinidad and Tobago", "demonym": "Trinidadian and Tobagonian" },
{ "name": "Tunisia", "demonym": "Tunisian" },
{ "name": "Turkey", "demonym": "Turkish" },
{ "name": "Turkmenistan", "demonym": "Turkmenistani" },
{ "name": "Turks and Caicos Islands", "demonym": "Turks and Caicos Islander" },
{ "name": "Tuvalu", "demonym": "Tuvaluan" },
{ "name": "Uganda", "demonym": "Ugandan" },
{ "name": "Ukraine", "demonym": "Ukrainian" },
{ "name": "United Arab Emirates", "demonym": "Emirati" },
{ "name": "United Kingdom", "demonym": "British" },
{ "name": "United States Minor Outlying Islands", "demonym": "American Islander" },
{ "name": "United States", "demonym": "American" },
{ "name": "Uruguay", "demonym": "Uruguayan" },
{ "name": "Uzbekistan", "demonym": "Uzbek" },
{ "name": "Vanuatu", "demonym": "Vanuatuan" },
{ "name": "Venezuela", "demonym": "Venezuelan" },
{ "name": "Vietnam", "demonym": "Vietse" },
{ "name": "Virgin Islands of the United States", "demonym": "Virgin Islander" },
{ "name": "Wallis and Futuna", "demonym": "Wallisian" },
{ "name": "Western Sahara", "demonym": "Western Saharan" },
{ "name": "Yemen", "demonym": "Yemeni" },
{ "name": "Zambia", "demonym": "Zambian" },
{ "name": "Zimbabwe", "demonym": "Zimbabwean" }]


export {CountryData}


